"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const senderEmail_controller_1 = require("../controllers/senderEmail.controller");
const Auth_middlewares_1 = require("../middlewares/Auth.middlewares");
const senderRouter = (0, express_1.Router)();
const controller = new senderEmail_controller_1.SenderEmailController();
senderRouter.post("/", Auth_middlewares_1.isAuthenticated, controller.createSenderEmail);
senderRouter.get("/", Auth_middlewares_1.isAuthenticated, controller.getAllSenderEmails);
senderRouter.get("/:id", Auth_middlewares_1.isAuthenticated, controller.getSenderEmailById);
senderRouter.put("/:id", Auth_middlewares_1.isAuthenticated, controller.updateSenderEmail);
senderRouter.delete("/:id", Auth_middlewares_1.isAuthenticated, controller.deleteSenderEmail);
senderRouter.post("/verify", Auth_middlewares_1.isAuthenticated, controller.verifySender);
exports.default = senderRouter;
